name: Committer Code Coverage Summary
author: Petra Barus
description: >
  This GitHub Action will analyze code coverage and print the summary per
  committer to the Pull Request.
inputs:
  github_token:
    description: 'The default GitHub token (secrets.GITHUB_TOKEN). We need this to post a comment to the PR as the bot.'
    required: true
    default: ${{ github.token }}
  coverage_files:
    description: |
      The list of coverage files to be analyzed. 
      The coverage files should be in the format of `path/to/coverage.xml`.
      Multiple coverage files can be provided by separating them with a comma.
    required: false
    default: "coverage.xml"
  min_threshold:
    description: |
      The minimum threshold for the committers' code coverage percentage. 
      If the code coverage percentage of a committer is below this threshold, 
      the committer will be considered as a failing committer.
    required: false
    default: "80"
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
