name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        run: rustup update stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - name: Install Rust Clippy and Rust Sonar
        run: |
          rustup component add clippy
          cargo install cargo-sonar

      - name: Generate code coverage lcov
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Generate code coverage cobertura
        run: cargo llvm-cov --all-features --workspace --cobertura --output-path coverage.xml

      - name: Coverage Stats
        uses: petrabarus/github-action-committer-coverage-stats@main

      - name: Generate Reports
        run: |
          cargo clippy --message-format json > clippy-report.json
          cargo sonar --clippy --clippy-path clippy-report.json

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            lcov.info
            coverage.xml

      - name: Install cargo-sonar
        run: |
            cargo install cargo-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dcommunity.rust.lcov.reportPaths=lcov.info
            -Dcommunity.rust.clippy.reportPaths=clippy-report.json
            -Dsonar.externalIssuesReportPaths=sonar-issues.json

  release:
    runs-on: ubuntu-latest
    needs: 
      - build
    permissions:
      contents: read
      packages: write # Enable the workflow to publish to docker registry
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}